experiment:
  random_seed: 42
  total_experimental_tickets: 200  # Ihre perfekten 200 Tickets
  min_tickets_per_category: 50     # Exakt 50 pro Kategorie
  min_per_condition: 25            # 200/8 = 25 (optimal für Statistik)
  min_total_tickets: 200           # Exakt verfügbar
  validation_split: 0.2
  
design:
  factorial_design: "2x4x2"        # LLM × Few-Shot × Prompt
  
models:
  - "llama3.1:8b"
  - "mistral:7b"

few_shot_counts: [0, 1, 3, 5]      # Komplette Few-Shot Progression
prompt_types: ["structured", "unstructured"]

llm_params:
  temperature: 0.1                 # Niedrig für Konsistenz
  top_p: 0.9
  max_tokens: 50

# Qualitätskontrolle für wissenschaftliche Rigorosität
quality_control:
  min_ticket_length: 20            # Mindestzeichen pro Ticket
  max_retry_attempts: 3            # LLM Retry-Versuche
  timeout_seconds: 45              # Timeout pro Request
  response_validation: false       # PROBLEM: Zu restriktiv - deaktiviert
  
# Statistische Parameter
statistics:
  alpha_level: 0.05               # Signifikanzniveau
  power_target: 0.80              # Angestrebte statistische Power
  effect_size_threshold: 0.30     # Cohen's f Threshold
  bonferroni_correction: true     # Multiple Comparison Correction

# Ollama-Verbindung
ollama:
  base_url: "http://localhost:11434"
  timeout: 45                     # Erhöht für Stabilität

# Kategorien für IT-Support-Tickets
categories:
  - "Hardware"
  - "Software" 
  - "Network"
  - "Security"

# Datei-Pfade
paths:
  data_dir: "data/"
  results_dir: "results/"
  # Haupt-Ticketdatei für wissenschaftliches Experiment
  ticket_file: "tickets_200.xlsx"
  # Few-Shot-Beispiel-Datei
  fewshot_file: "tickets_examples.xlsx"
  
# Prompt-Templates
prompts:
  structured_template: |
    Sie sind ein IT-Support-Experte. Ihre Aufgabe ist es, das folgende Ticket einer der untenstehenden Kategorien zuzuordnen.
    Kategorien:
    - Hardware: Probleme mit Geräten (z.B. Laptop, Drucker, Monitor)
    - Software: Probleme mit Programmen (z.B. Excel, VPN, Email)
    - Network: Probleme mit Netzwerk (z.B. Internet, WLAN, Server)
    - Security: Sicherheitsprobleme (z.B. Phishing, Passwort, Malware)
    
    Ticket: {ticket_text}
    
    Bitte geben Sie nur die Kategorie an:
  unstructured_template: |
    Was für ein IT-Problem ist das? Mögliche Kategorien: Hardware, Software, Network, Security.
    {ticket_text}
    Antwort: